GET http://localhost:3300
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE1OTI5OTYxNjIsImV4cCI6MTU5Mjk5NjE3NywiYXVkIjoiNWVlYTBlOTlkMTU3ZjYzZjNlMzYxYjQxIiwiaXNzIjoicGlja3VycGFnZS5jb20ifQ.fsED23a_2dINM1saPjmHkc_gVrsuptb1oSNh0GR-03M

### Login Route
# 구글토큰 => 서버확인 => 사용자정보 리턴
# 이메일로 사용자 찾기 => 액세스, 리프레쉬 토큰 생성 후 클라이언트로 리턴
# 굳이 클라->서버로 보내는 정보가 따로 없다면 GET으로
# 그런데 문맥상 레디스에 저장을 하니까 POST가 맞는듯?
POST http://localhost:3300/api/common/v1/login
Authorization: Bearer {{google_token}}
Content-Type: application/json

###Refresh token Route
# 언제? : access 토큰이 만료가 되었거나 없는 경우
# 받은 refresh 토큰을 검증 => 사용자정보 리턴
# 새로운 access Token, refresh Token 생성 => 클라 리턴
POST http://localhost:3300/api/common/v1/refresh-token
Content-Type: application/json

{
  "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MjIsImVtYWlsIjoiaHl1bmpvb2dvQGdtYWlsLmNvbSIsIm5hbWUiOiLquYDtmITso7wiLCJpYXQiOjE2ODIxMzcxOTksImV4cCI6MTcxMzY5NDc5OSwiYXVkIjoiMjIiLCJpc3MiOiJWYWNheS1NYXRlIn0.UVwsnB8Adkfmd_CSYrfk4j8aTcobkDB10vs-MjEgPXE"
}
