###
// https://sihyung92.oopy.io/etc/intellij/2
// https://jwt.io/

### '/'
GET {{host}}/

### 회원 로그인
GET {{host}}/login
Authorization: Bearer {{access_token}}
Content-Type: application/json

### 휴가유형 생성
POST {{host}}/vacation/{{hyunjoogo_id}}
Authorization: Bearer {{access_token}}
Content-Type: application/json

{
  "type": "summer",
  "totalDays": 5,
  "leftDays": 5,
  "expirationDate": "2024-12-31"
}

### 전체 사용자의 휴가유형 리스트
GET {{host}}/vacation?sort=created_at
Authorization: Bearer {{access_token}}

### 하나의 사용자의 휴가유형 리스트
GET {{host}}/vacation/{{hyunjoogo_id}}
Authorization: Bearer {{access_token}}

### 사용자의 휴가사용요청
POST {{host}}/request/{{hyunjoogo_id}}
Authorization: Bearer {{access_token}}
Content-Type: application/json

{
  "type": "annual",
  "useType": "dayOff",
  "startDate": "2023-06-23",
  "endDate": "2023-06-25",
  "status": "pending"
}


### 휴가사용요청 목록
GET {{host}}/request
Authorization: Bearer {{access_token}}
Content-Type: application/json

### 휴가사용요청 이름만 검색
GET {{host}}/request?page=1&limit=10&name=김현주
Authorization: Bearer {{access_token}}
Content-Type: application/json

### 이름검색
GET {{host}}/request?page=1&limit=10&name=김현주
Authorization: Bearer {{access_token}}
Content-Type: application/json

### 아무 조건없는 검색
GET {{host}}/request?page=1&limit=10
Authorization: Bearer {{access_token}}
Content-Type: application/json

### 이름+type(name=김현, type="annual") 검색
GET {{host}}/request?page=1&limit=10&type=annual&name=김현
Authorization: Bearer {{access_token}}
Content-Type: application/json

### 휴가요청 상세조회
GET {{host}}/request/64285b152cac545f5125ceec
Authorization: Bearer {{access_token}}
Content-Type: application/json

