###
// https://sihyung92.oopy.io/etc/intellij/2
// https://jwt.io/

### '/'
GET {{host}}/

### 회원 로그인
GET {{host}}/login
Authorization: Bearer {{access_token}}
Content-Type: application/json

### 시스템 휴가유형 생성
POST {{host}}/api/vacation
Authorization: Bearer {{access_token}}
Content-Type: application/json

{
  "name": "여름휴가-2023",
  "expirationDate": "2023-12-31",
  "memo": "2023년도 여름휴가분"
}

### 관리자 -> 사용자 휴가 유형 생성
POST {{host}}/api/user/vacation-type
Authorization: Bearer {{access_token}}
Content-Type: application/json

{
  "userId": 1,
  "vacationTypeId": 1,
  "remainingDays": 5,
  "totalDays": 5,
  "expirationDate": "2023-12-31"
}


