### 사용자 등록
POST {{host}}/api/register/{{ver}}
Authorization: Bearer {{access_token}}
Content-Type: application/json

{
  "name": "조윤심",
  "email": "postam@gmail.com"
}


### 사용자 상세조회: 나의 정보
GET {{host}}/api/user/{{ver}}/profile/1
Authorization: Bearer {{access_token}}
Content-Type: application/json
