### 사용자 등록
POST {{host}}/api/register/{{ver}}
Authorization: Bearer {{access_token}}
Content-Type: application/json

{
  "name": "조윤심",
  "email": "postam@gmail.com"
}


### 사용자 상세조회: 나의 정보
GET {{user}}/{{user_id}}/profile
Authorization: Bearer {{access_token}}
Content-Type: application/json

### 사용자 휴가종류 조회
GET {{user}}/{{user_id}}/vacation
Authorization: Bearer {{access_token}}
Content-Type: application/json

### 사용자 휴가종류 상세조회
GET {{user}}/{{user_id}}/vacation/22
Authorization: Bearer {{access_token}}
Content-Type: application/json

### 사용자 휴가사용요청 조회
GET {{user}}/{{user_id}}/request
Authorization: Bearer {{access_token}}
Content-Type: application/json

### 사용자 휴가사용요청 등록#1 (같은 유형의 휴가만 가능)
POST {{user}}/{{user_id}}/request
Authorization: Bearer {{access_token}}
Content-Type: application/json

{
  "requests": [
    {
      "useDate": "2023-04-16",
      "usingType": "일차",
      "usingDay" : 1
    },
    {
      "useDate": "2023-04-17",
      "usingType": "오후반차",
      "usingDay" : 0.5
    }
  ],
  "vacationId": 22,
  "totalDays": 1.5
}

### 사용자 휴가사용요청 등록#2 (같은 유형의 휴가만 가능)
POST {{user}}/{{user_id}}/request
Authorization: Bearer {{access_token}}
Content-Type: application/json

{
  "requests": [
    {
      "useDate": "2023-04-17",
      "usingType": "오전반차",
      "usingDay" : 0.5
    },
    {
      "useDate": "2023-04-18",
      "usingType": "일차",
      "usingDay" : 1
    }
  ],
  "vacationId": 22,
  "totalDays": 1.5
}

### 사용자 휴가사용요청 상세조회
GET {{user}}/{{user_id}}/request/1
Authorization: Bearer {{access_token}}
Content-Type: application/json

### 사용자 휴가요청 취소
POST {{user}}/{{user_id}}/request/cancel/1
