### 사용자 등록
POST {{host}}/api/register/{{ver}}
Authorization: Bearer {{access_token}}
Content-Type: application/json

{
  "name": "조윤심",
  "email": "postam@gmail.com"
}


### 사용자 상세조회: 나의 정보
GET {{user}}/{{user_id}}/profile
Authorization: Bearer {{access_token}}
Content-Type: application/json

### 사용자 휴가종류 조회
GET {{user}}/{{user_id}}/vacation
Authorization: Bearer {{access_token}}
Content-Type: application/json

### 사용자 휴가사용요청 조회
GET {{user}}/{{user_id}}/request
Authorization: Bearer {{access_token}}
Content-Type: application/json

### 사용자 휴가사용요청 등록
POST {{user}}/{{user_id}}/request
Authorization: Bearer {{access_token}}
Content-Type: application/json

{
  "vacationId": 1,
  "useDate" : "2023-04-13",
  "usingType" : "일차",
  "memo" : "테스트 일차"
}
